version: '3'

tasks:
  run:
    - ./torrex
  build:
    cmds:
      - cd web && npm run build
      - rm -rf dist
      - cp -r -f web/dist ./dist
      - go build
    silent: true
  default:
    cmds:
      - go run .
  web:
    cmds:
      - cd web && npm run dev